image: php:latest

stages:
  - test

before_script:
  - apt-get update && apt-get install -y git unzip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - composer install --prefer-dist --no-interaction

test:
  stage: test
  script:
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text
